name: autolist
description: Animated list views, automatically.
  Autolist transforms regular dart lists them into a fully
  animated list views, automatically managing insertions and deletions.
version: 0.1.1
homepage: https://gitlab.com/benweitzman/autolist/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: